# cmdiff default configuration file
#
# configuration file version
version: 1
#
# logging configuration
#
# for available options see: https://github.com/gogap/logrus_mate
#
# log level
level: debug
# log output formatter
formatter.name: text
#
################################################################################
#
#  Filewalker module - collect (local) file list into current session
#
filewalker:
#
# The glob pattern syntax is:
#   pattern:
#       { term }
#
#   term:
#       `*`         matches any sequence of non-separator characters
#       `**`        matches any sequence of characters
#       `?`         matches any single non-separator character
#       `[` [ `!` ] { character-range } `]`
#                   character class (must be non-empty)
#       `{` pattern-list `}`
#                   pattern alternatives
#       c           matches character c (c != `*`, `**`, `?`, `\`, `[`, `{`, `}`)
#       `\` c       matches character c
#
#   character-range:
#       c           matches character c (c != `\\`, `-`, `]`)
#       `\` c       matches character c
#       lo `-` hi   matches character c for lo <= c <= hi
#
#   pattern-list:
#       pattern { `,` pattern }
#                   comma-separated (without spaces) patterns
#
# include files matching patterns (array of glob patterns)
  include:
    - '/opt/**conf**'
    - '/etc/**'
    - '/bin/**'
    - '/sbin/**'
    - '/usr/bin/**'
    - '/usr/sbin/**'
#
# exclude files from list defined by the "include" directive (array of glob patterns)
  exclude:
    - '/etc/mtab'
    - '/etc/ld.so.cache'
    - '/etc/printcap'
    - '**.bak'
    - '**~'
#
# FileContentLoader module - optionally loads content of files collected by filewalker for detailed reporting
#
filecontentloader:
  # size limit in bytes - loaded files must fit in memory
  # allowed size multipliers: k - kilobytes, m - megabytes, g - gigbabytes - see https://github.com/cloudfoundry/bytefmt
  sizeLimit: 512k
  include:
   - '/etc/**'
   - '**.{co?nf,xml,ya?ml,txt}'
  exclude:
   - '/etc/g?shadow*'
   - '**.{secret,key}'
#
# Diff ignore rules - diff.ignore.[attr] contains list of glob patterns
# matching paths for which attr shall be ignored during diff
#
diff.ignore:
  hasher.error:
   - '**'
  content.error:
   - '**'
  modTime:
   - '/etc/cups/subscriptions.conf**'
  stat.atime:
   - '/etc/cups/subscriptions.conf**'
  stat.ctime:
   - '/etc/cups/subscriptions.conf**'
#
# Database options
#
db:
  basepath: /var/tmp/cmdiff.db
  maxSessions: 3
#
# Report options
#
report.template: |
  Report {{ diff.Meta.Time.String }} ({{ diff.Meta.UUID.String }})
  "Old" session: {{ diff.Meta.OldSession.Time.String }} ({{ diff.Meta.OldSession.UUID.String }})
  "New" session:  {{ diff.Meta.NewSession.Time.String }} ({{ diff.Meta.NewSession.UUID.String }})
  Items Lost: {{ diff.Meta.ItemsLost }} / Found: {{ diff.Meta.ItemsFound }} / Equal: {{ diff.Meta.ItemsEqual }} / Different: {{ diff.Meta.ItemsDiff }}
  Total item changes: {{ diff.Meta.Changes }}
